const articles = [
  {
    name: "Vue-Router",
    title: "Composing Layouts with Vue Router",
    date: "01 april 2023",
    desc: "DailyTech blogs for Composing Layouts with Vue Router",
    author: "swastik_giri",
    authorlink:
      "https://vueschool.io/articles/vuejs-tutorials/composing-layouts-with-vue-router/",
    img: "https://blog.vueschool.io/wp-content/uploads/2022/02/composing-layouts-with-vue-router-social.jpg",
    content: [
      `Vue Router is the de facto standard for creating routes in Vue.js SPA’s. Did you know though, that besides using it to map routes to page components, you can also use it to compose page layouts? That’s an interesting proposal. Let’s see how it’s done.Let’s say we’re building a blog where there’s the potential for some pages to have a sidebar on each side of the main content.`,
      `Super fast and of course we have injection with auto generated SEO for this project, yes.. we use helmet !!`,
      `With this concept so you can just focusing on your content article .`,
      `Cuteblog react adalah sebuah tema dan template yang khusus diperuntukan untuk library react js, dan dengan tema ini tentunya harapan kami selaku pengembang memudahkan mu untuk membuat webiste dan blog dengan cepat. `,
      `Persembahan dari axcora technology untuk dunia agar dapat membuat sebuah website dan blog modern berbasis react dengan konsep blog.`,
    ],
  },
  {
    name: "gatsby-js",
    title: "Gatsby JS",
    desc: "Cuteblog for Gatsby with react JS",
    date: "02 april 2023",
    author: "swastik_giri",
    authorlink: "https://swastikgiri.vercel.app/",
    img: "https://evilmartians.com/static/d20006f3d92f33931ef5caa8e61bc91f/b73de/cover.avif",
    content: [
      `If you love gatsby js so stay tuned.. next we develope cuteblog to using gatsby js, of course same concept and design with cuteblog.`,
      `Dan ya bagi kamu pencinta gatsby js maka tunggu project kami selanjutnya untuk cuteblog themes template menggunakan gatsby, dan pastinya gratis untuk kamu unduh full source code free download.`,
    ],
  },
  {
    name: "REACT-PROJECT",
    title: "React Libraries",
    date: "03 april 2023",
    author: "swastik_giri",
    authorlink: "https://swastikgiri.vercel.app/",
    img: "https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    desc: "HOW TO CREATE A REACT PROJECT",
    content: [
      `There is this unknown for every React beginner on how to set up a React project when joining the React world. There are many frameworks to choose from. The most popular choice in the React community is Vite which allows you to create projects with various library (e.g. React) + opt-in TypeScript combinations. It comes with incredible performance.`,
      `Oke after installation you need to download cuteblog react source code on or github repo, just github icon click button on navbar. or you can using git bash with run git clone https://github.com/mesinkasir/cuteblogreact.git `,
      `Now extract all source code project and you need to install with run npm install && npm start , then open localhost:3000 , congratulation now you have success installing cuteblog for react on your devices. `,
    ],
  },
  {
    name: "Advanced-Data-Fetching",
    title: "Advanced Data Fetching in Vue w/ TanStack Query",
    date: "04 april 2023",
    author: "swastik_giri",
    authorlink: "https://swastikgiri.vercel.app/",
    img: "https://miro.medium.com/v2/resize:fit:750/format:webp/1*o7EQBslbC7iywso5_Bk3tA.jpeg",
    desc: "In the Vue world, we don’t really have an opinionated way of how to handle advanced data fetching.",
    content: [
      `We mostly rely on libraries like Axios to handle the actual creation of the requests, but after that we are left to our own devices in terms of handling how to process that data. There have not been standards for processes beyond fetching, such as caching, synchronizing and updating server state, etc…`,
      `For SEO you can visit on index.js file and change title description and other on helmet .`,
    ],
  },
  {
    name: "Blue-Green-Deployment ",
    title: "Deploy",
    date: "05 april 2022",
    author: "swastik_giri",
    authorlink: "https://swastikgiri.vercel.app/",
    img: "https://miro.medium.com/v2/resize:fit:750/format:webp/1*2VfJFoYekJbnR4mF1aV9MA.png",
    desc: "Blue Green Deployment for Node.js Without Kubernetes",
    content: [
      `The Blue Green Deployment strategy allows for the testing of new deployments with production data before making them available to users. This type of deployment also has the added benefit of having no downtime during the deployment process.`,
      `For using firebase and surge for first you need to build to production mode, so you can input this command on shell terminal npm run build - then you can deploy on public folder to firebase or surge .`,
      `Option two you can use github intergation with heroku,vercel,netlify - just create account and create new repo and push your source code to your repo project, and you need to integration with netlify ,heroku or vercel, just create new project then select your github repo and deploy it. `,
    ],
  },
  {
    name: "useState-Hell",
    title: "A Cure for React useState Hell?",
    date: "06 april 2022",
    author: "swastik_giri",
    authorlink: "https://swastikgiri.vercel.app/",
    img: "https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fa66e640329e847cdb739e1c9475d2484",
    desc: "A Cure for React useState Hell?",
    content: [
      `Did you know that there is an alternative state hook that is more powerful and easier to use than you might think?`,
      `Using useReducer, we could transform the above code, to just this:`,
      `Cuteblog for jekyll`,
      `https://www.hockeycomputindo.com/2022/04/auto-seo-dengan-cuteblog-for-jekyll.html`,
      `Cuteblog for eleventy`,
      `https://www.hockeycomputindo.com/2022/04/cuteblog-11ty-for-eleventy-generator.html`,
      `Cuteblog for astro`,
      `https://www.hockeycomputindo.com/2022/04/cute-blog-astro-generator-static-site.html`,
      `Cuteblog for pico cms`,
      `https://www.hockeycomputindo.com/2022/04/tema-blog-website-terbaru-dan-gratis.html`,
    ],
  },
  {
    name: "css ",
    title: "5 ways CSS :has() can make your HTML forms even better",
    date: "05 april 2022",
    author: "swastik_giri",
    authorlink: "https://swastikgiri.vercel.app/",
    img: "https://austingil.com/wp-content/uploads/CSS%20Blog%20Cover.svg",
    desc: "can make your HTML forms even better",
    content: [
      `The Blue Green Deployment strategy allows for the testing of new deployments with production data before making them available to users. This type of deployment also has the added benefit of having no downtime during the deployment process.`,
      `For using firebase and surge for first you need to build to production mode, so you can input this command on shell terminal npm run build - then you can deploy on public folder to firebase or surge .`,
      `Option two you can use github intergation with heroku,vercel,netlify - just create account and create new repo and push your source code to your repo project, and you need to integration with netlify ,heroku or vercel, just create new project then select your github repo and deploy it. `,
    ],
  },
  {
    name: "cloud",
    title: "Cloud with Us",
    date: "08 april 2022",
    author: "swastik_giri",
    authorlink: "https://swastikgiri.vercel.app/",
    img: "https://media.istockphoto.com/vectors/multimedia-content-upload-interface-vector-id1299267805?k=20&m=1299267805&s=612x612&w=0&h=h2TKY77Vcd2144vvjYZbn2eTQr6XoHxDLPMKvI4jU7Q=",
    desc: "Create and build your modern website with us for best solutions",
    content: [
      `If you need to build and develop modern website using modern technology like static site generator with jekyll, eleventy 11ty , astro or user react, svelte kit, angular so you can use our services with cheap price`,
      `Or you need to create web app where website integration with your point of sale application so we can do it , with multiple technology let's get started build your website application including android app.`,
      `Contact Us`,
      `Whatsapp : +6285646104747`,
      `Call Us : +62895339403223`,
      `Email : axcora@gmail.com`,
    ],
  },
];

export default articles;
